### ISSUE TITLE
Using OpenVPN on top of Lightway

### ISSUE THREAD

**Issue by inliquid** [expressvpn/lightway-core#12]
Is it in general possible to put both Lightway (for instance by ExpressVPN) and OpenVPN (by another vpn provider) on top of each other to build a double vpn tunnel by running them simultaneously in the same OS? Maybe anyone experimented with such set-up?

**Comment by expressvpn-pete-m** [comment]
In principle there is nothing stopping you doing this, but you'd have to make sure that OpenVPN was configured so that it would handle the size limit of Lightway (`1350` bytes).

Most VPN providers assume that their application is the sole VPN running, and this could cause a number of conflicts.

Running your own OpenVPN connection over your own Lightway connection is certainly doable however :)
