### ISSUE TITLE
Hi, arm version for huawei routers!

### ISSUE THREAD

**Issue by mfricano2021** [expressvpn/lightway-core#20]
I would love to see running lightway on huawei routers like b525. Could it be compiled for arm architecture?

**Comment by expressvpn-pete-m** [comment]
Hi @mfricano2021 , Lightway does indeed compile for ARM as that is what we use on Android (see the included builds scripts). It looks like the B525 is fairly standard so compiling it shouldn't be a problem - indeed it might just work if you can compile it on the router itself (assuming it has enough resources). Otherwise you'd either need to cross compile it or use a tool like Earthly to run the build in a simulated environment.

If you do update the Earthfile to support such a build, we would welcome a PR to the repo :)

**Comment by mfricano2021** [comment]
Hi, how can I update the eartfile it should be arm 32 bit architecture. Many thanks

Scarica Outlook per Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by expressvpn-pete-m** [comment]
I'd start by checking out the multi platform documentation for Earthly:

https://docs.earthly.dev/docs/guides/multi-platform

The default build of WolfSSL we use on Linux has configuration options for certain AMD64 features that won't be available though. They should be easy to spot once you try building on arm32.

If you have time to work on a PR, I'd be happy to review it, but right now I can't work on this myself as I'm needed elsewhere :)

**Comment by expressvpn-pete-m** [comment]
I'm closing this for now, but feel free to reopen it if you're in a position to work on a PR with us :)
