### ISSUE TITLE
Some question about Lightway protocol

### ISSUE THREAD

**Issue by YT-Advanced** [expressvpn/lightway-core#90]
Dear dev team !
Thanks for this project and thanks to ExpressVPN team because of their hardworking. Lightway is powerful and fast but I think I have some question about this project, hope you answer it
1. What is `hash algorithm` that Lightway are using ?
As I have read, ExpressVPN use `SHA2-512`, so I recommend use `BLAKE2` instead
2. Can you explain about hand-shake step of Lightway ? I think you should use QUIC for faster hand-shake.
3. Does Lightway use asymmetric encryption for key-exchanging ? If not, please explain what client-server do in key-exchanging
4. Until now, Winderscribe and ProtonVPN have added Stealth protocol, which uses some tool like Stunnel to make VPN connection look like HTTPS. So why dev team don't add it ?
5. Lightway look like only have 1 thread, why don't you add support for multi-threading ?
6. When Lightway addded threading, I suggested Lightway spilit data when transfer and merge it again. By this way, hacker will difficult to arrange data and also speed up VPN Speed.
Last, thank you and hope you have a nice day !

**Comment by expressvpn-pete-m** [comment]
Hi,

Thanks for your questions!

1. Lightway uses either `AES256-GCM-SHA384`  or `CHACHA20-POLY1305-SHA256`. This is deliberately kept to a minimum selection for safety. 
2. Lightway uses TLS or DTLS and thus uses their handshakes. 
3. See question 2
4. Given that Lightway over TLS is already what an HTTPS connection looks like, there is nothing that needs to be done.
5. Because multi-threading adds complexity, and Lightway is already extremely fast even with a single thread. Our Rust version however is full asynchronous and will be able to take advantage of multiple threads.
6. There is an interesting paper on this topic already called [Multipath Encrypted Overlay](https://tklab.feit.uts.edu.au/~darryl/Publications/BDWC_ISITA2014_camera.pdf). This is an active area of interest for the field.

Hope this answers some of your questions! :slightly_smiling_face:

**Comment by YT-Advanced** [comment]
Thanks for your reply, as you said in 5, no need to add multi-threading. But it will cause a problem:
When I open multi tab to load, only one of them is loaded (I have reported it to ExpressVPN Support but seem like it is not fixed)

**Comment by expressvpn-pete-m** [comment]
Lightway Laser uses `libuv` which provides a reactor style implementation for high performance I/O. It sits at the core of many high performance applications. Being single threaded here means that Lightway can only take advantage of a single CPU core at a time. As most people have CPUs far faster than their network connections, it's relatively rare that anyone would hit the performance limit in daily use.

In your case, I'm not sure what exactly you're experiencing. By tabs are you referring to browser tabs? If so, this should not be affected by Lightway. If you mean you are trying to connect to the same Lightway Laser Server with two clients simultaneously, then this is expected behaviour because it is just a reference client and server - it only supports a single connection in order to keep its code as simple as possible.

The new client and server that we are working on will be more fully featured and will not have this limitation.

**Comment by YT-Advanced** [comment]
> In your case, I'm not sure what exactly you're experiencing. By tabs are you referring to browser tabs? If so, this should not be affected by Lightway. If you mean you are trying to connect to the same Lightway Laser Server with two clients simultaneously, then this is expected behaviour because it is just a reference client and server - it only supports a single connection in order to keep its code as simple as possible.

I mean browser tabs. I don't know why but when connect via OpenVPN, all thing work flawlessly. But with Lightway, for some unknow reason, only one tabs can be loaded at the same time

**Comment by YT-Advanced** [comment]
> I don't really have any good explanations for why you might see this behaviour. Have you tried opening the same site in both tabs? Have you tried two different browsers at once? Does other traffic (such as DNS and Ping) still get through?

Soemtimes I open multi Github tab to do my work. When open VPN, only one tab can be loaded and when turn off all work normally. Maybe it only occur on my device so I will close this issues
